apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: netroll
  labels:
    team: nais
spec:
  image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 64Mi
