apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: netroll-apiserver
spec:
  egress:
    - ports:
        - port: 443
          protocol: TCP
      to:
        - ipBlock:
            cidr: {{ .Values.apiserverIP }}/32
  podSelector:
    matchLabels:
      app: netroll
  policyTypes:
    - Egress
