apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: netroll-apiserver
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 172.16.1.2/32
  podSelector:
    matchLabels:
      app: netroll
  policyTypes:
  - Egress
