apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: instance
spec:
  databaseVersion: POSTGRES_14
  region: europe-north1
  resourceID: contests
  settings:
    activationPolicy: ALWAYS
    availabilityType: ZONAL
    backupConfiguration:
      backupRetentionSettings:
        retainedBackups: 7
        retentionUnit: COUNT
      enabled: true
      pointInTimeRecoveryEnabled: false
      startTime: "02:00"
      transactionLogRetentionDays: 7
    databaseFlags:
    - name: cloudsql.iam_authentication
      value: "on"
    diskAutoresize: false
    diskAutoresizeLimit: 0
    diskSize: 10
    diskType: PD_SSD
    insightsConfig:
      queryInsightsEnabled: true
      queryStringLength: 1024
      recordApplicationTags: false
      recordClientAddress: false
    ipConfiguration:
      ipv4Enabled: true
      requireSsl: true
    locationPreference:
      zone: europe-north1-a
    pricingPlan: PER_USE
    replicationType: SYNCHRONOUS
    tier: db-f1-micro
