apiVersion: v2
name: netroll
description: Creates network policies to allow communication from application to database
sources:
  - github.com/nais/netroll/tree/main/charts/netroll
type: application
version: 1.0.1
