name: Build and push image and chart

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:

env:
  NAME: netroll
  IMAGE_REPOSITORY: oci://europe-north1-docker.pkg.dev/nais-io/nais

jobs:
  build_push:
    outputs:
      version: ${{ steps.build-push-sign.outputs.version }}
    permissions:
      contents: "read"
      id-token: "write"
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: nais/platform-build-push-sign@main
        id: build-push-sign
        with:
          name: ${{ env.NAME }}
          google_service_account: gh-${{ env.NAME }}
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          push: ${{ github.ref == 'refs/heads/main' && github.actor != 'dependabot[bot]' }}
          cache_from: type=gha
          cache_to: type=gha,mode=max
      - uses: azure/setup-helm@v3
        name: "Setup Helm"
        with:
          version: "3.12.0"
      - name: Build Chart
        run: |-
          yq e '.version = "${{ steps.build-push-sign.outputs.version }}"' --inplace "charts/Chart.yaml"
          cat charts/Chart.yaml
          helm package charts
      - name: Push Chart
        if: github.ref == 'refs/heads/main'
        run: |-
          helm push ${{ env.NAME }}*.tgz ${{ env.IMAGE_REPOSITORY }}/feature

  rollout:
    if: github.actor != 'dependabot[bot]' && github.ref == 'refs/heads/main'
    needs:
      - build_push
    runs-on: fasit-deploy
    permissions:
      id-token: write
    steps:
      - uses: nais/fasit-deploy@v2
        with:
          chart: ${{ env.IMAGE_REPOSITORY }}/feature/${{ env.NAME }}
          version: ${{ needs.build_push.outputs.version }}
          feature_name: ${{ env.NAME }}
