name: Build and push image and chart
on:
  push:
    branches:
      - main

env:
  NAME: netroll
  REGISTRY: europe-north1-docker.pkg.dev/nais-io/nais/images
  BUILDER_IMG: "cgr.dev/chainguard/go:1.19"
  RUNNER_IMG: "cgr.dev/chainguard/static"
  BASEIMG_IDENTITY: "https://github.com/chainguard-images/images/.github/workflows/release.yaml@refs/heads/main"
  BASEIMG_ISSUER: "https://token.actions.githubusercontent.com"

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install cosign
        uses: sigstore/cosign-installer@9e9de2292db7abb3f51b7f4808d98f0d347a8919 # ratchet:sigstore/cosign-installer@main
        with:
          cosign-release: 'v2.0.0'
      - name: Verify builder image
        run: cosign verify --certificate-identity ${{ env.BASEIMG_IDENTITY }} --certificate-oidc-issuer ${{ env.BASEIMG_ISSUER }} ${{ env.BUILDER_IMG }}
      - name: Verify runner image
        run: cosign verify --certificate-identity ${{ env.BASEIMG_IDENTITY }} --certificate-oidc-issuer ${{ env.BASEIMG_ISSUER }} ${{ env.RUNNER_IMG }}
      - name: Create new version
        run: |
          echo "NEW_VERSION: $(date '+%Y.%-m.%-d')-$(git rev-parse --short HEAD)"
          echo "NEW_VERSION=$(date '+%Y.%-m.%-d')-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "# Created version: $(date '+%Y.%-m.%-d')-$(git rev-parse --short HEAD)" >> $GITHUB_STEP_SUMMARY
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: "gh-${{ env.NAME }}@nais-io.iam.gserviceaccount.com"
          token_format: "access_token"
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ${{ env.REGISTRY }}
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
      - name: Build and push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.NAME }}:${{ env.NEW_VERSION }},${{ env.REGISTRY }}/${{ env.NAME }}:latest
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ env.NEW_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: azure/setup-helm@v1
        name: "Setup Helm"
        with:
          version: "3.8.0"
      - name: Build Chart
        run: |-
          sed -i "s/^version: .*/version: ${{ env.NEW_VERSION }}/g" feature/Chart.yaml
          cat feature/Chart.yaml
          helm package feature
      - name: Push Chart
        run: |-
          helm push ${{ env.NAME }}*.tgz oci://europe-north1-docker.pkg.dev/nais-io/nais
